### ISSUE TITLE
[3.0.3-beta] Error with quickstart

### ISSUE THREAD

**Issue by nico4github** [ucl-exoplanets/TauREx3_public#5]
Hello,

I'm new to TauREx so I was trying to follow:
https://taurex3-public.readthedocs.io/en/latest/user/taurex/quickstart.html

I installed TauREx, ran the following command to validate installation:
$python -c "import taurex; print(taurex.__version__)"
3.0.3-beta

I downloaded the entire dropbox volume that contain xsec and cia, and modify the .par file to reflect their location on my system.

When I run your quickstart command I get an error.
I pasting the whole command line output for your review below.

Thanks,
Nicolas

---

$ taurex -i examples/parfiles/quickstart.par --plot
taurex - INFO - TauREx 3.0.3-beta
taurex - INFO - TauREx PROGRAM START AT 2020-10-23 12:44:25.618512
taurex.ParamParser - INFO - Interpolation mode set to linear
taurex.ParamParser - WARNING - Xsecs will be loaded in memory
taurex.ParamParser - WARNING - Radis is disabled
taurex.ParamParser - WARNING - Radis default grid will be used
taurex.TransmissionModel - INFO - Building model........
taurex.TransmissionModel - INFO - Collecting paramters
taurex.TransmissionModel - INFO - Setting up profiles
taurex.TransmissionModel - INFO - Computing pressure profile
taurex.ChemistryModel - INFO - Initializing chemistry model
taurex.ChemistryModel - INFO - Initializing chemistry model
taurex.TransmissionModel - INFO - Setting up contributions
taurex.TransmissionModel - INFO - DONE
taurex.TransmissionModel - ERROR - No active molecules detected
taurex.TransmissionModel - ERROR - Most likely no cross-sections were detected
Traceback (most recent call last):
  File "/Users/ngorius/opt/miniconda3/bin/taurex", line 8, in <module>
    sys.exit(main())
  File "/Users/ngorius/opt/miniconda3/lib/python3.7/site-packages/taurex/taurex.py", line 98, in main
    wngrid = model.nativeWavenumberGrid
  File "/Users/ngorius/opt/miniconda3/lib/python3.7/site-packages/taurex/model/simplemodel.py", line 356, in nativeWavenumberGrid
    raise InvalidModelException('No active absorbing molecules')
taurex.exceptions.InvalidModelException: No active absorbing molecules

**Comment by nico4github** [comment]
Sorry. I just realized that a previously closed issue was addressing this problem already.
I edited the .par file to point to the directory that contains pickle and db files from xsec and cia. It works.
